package com.entity;

import java.util.Date;

public class TrainInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_info.train_no
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    private String trainNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_info.start_station
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    private String startStation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_info.arrival_station
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    private String arrivalStation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_info.start_time
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_info.arrival_time
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    private String arrivalTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_info.TYPE
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_info.runtime
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    private Date runtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train_info.mile
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    private String mile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_info.train_no
     *
     * @return the value of train_info.train_no
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    public String getTrainNo() {
        return trainNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_info.train_no
     *
     * @param trainNo the value for train_info.train_no
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    public void setTrainNo(String trainNo) {
        this.trainNo = trainNo == null ? null : trainNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_info.start_station
     *
     * @return the value of train_info.start_station
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    public String getStartStation() {
        return startStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_info.start_station
     *
     * @param startStation the value for train_info.start_station
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    public void setStartStation(String startStation) {
        this.startStation = startStation == null ? null : startStation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_info.arrival_station
     *
     * @return the value of train_info.arrival_station
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    public String getArrivalStation() {
        return arrivalStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_info.arrival_station
     *
     * @param arrivalStation the value for train_info.arrival_station
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    public void setArrivalStation(String arrivalStation) {
        this.arrivalStation = arrivalStation == null ? null : arrivalStation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_info.start_time
     *
     * @return the value of train_info.start_time
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_info.start_time
     *
     * @param startTime the value for train_info.start_time
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_info.arrival_time
     *
     * @return the value of train_info.arrival_time
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    public String getArrivalTime() {
        return arrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_info.arrival_time
     *
     * @param arrivalTime the value for train_info.arrival_time
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    public void setArrivalTime(String arrivalTime) {
        this.arrivalTime = arrivalTime == null ? null : arrivalTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_info.TYPE
     *
     * @return the value of train_info.TYPE
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_info.TYPE
     *
     * @param type the value for train_info.TYPE
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_info.runtime
     *
     * @return the value of train_info.runtime
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    public Date getRuntime() {
        return runtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_info.runtime
     *
     * @param runtime the value for train_info.runtime
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    public void setRuntime(Date runtime) {
        this.runtime = runtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train_info.mile
     *
     * @return the value of train_info.mile
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    public String getMile() {
        return mile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train_info.mile
     *
     * @param mile the value for train_info.mile
     *
     * @mbggenerated Thu Aug 09 14:34:49 CST 2018
     */
    public void setMile(String mile) {
        this.mile = mile == null ? null : mile.trim();
    }
}